### ISSUE TITLE
Duration incorrect

### ISSUE THREAD

**Issue by ardunster** [CodeMouse92/Timecard#23]
I'll test further next time I need to measure some time. Tried the app out today since the one I was using was annoying me endlessly.  The timer at the top of the screen showed the correct duration from 10:53 am to 12:15 pm of 1:22. However, after saving to the log and then going in the settings and finding the "show duration in decimal" option and saving that, I went back to the log screen to discover it listed a duration of 2.25 which was clearly incorrect.  I didn't notice what it said before I went in the settings menu, but disabling and reenabling the decimal function continues to give a quantity of two and one quarter hours in whichever notation.  

The log file has only this: 
```
2020-10-24-10-53-58|02:15:34|task
```
2.25 hours have not even passed since starting the tracker until the moment I'm writing this, so I'm not clear on just what happened. (I experimentally timed another 4 minutes while writing this and doing a couple other things which logged correctly, but didn't go over an hour)

I'll let you know if I can reproduce the error and under what circumstances. :)

**Comment by CodeMouse92** [comment]
Cool, keep me posted. Thanks.

**Comment by ardunster** [comment]
Today's experience indicates that probably duration is recording the time from loading the program to saving the data, rather than the actual time actively recorded:

![Screenshot from 2020-10-26 15-32-06](https://user-images.githubusercontent.com/61255483/97236004-636a0c80-17a1-11eb-8b96-33c35cd6ad18.png)
![Screenshot from 2020-10-26 15-31-28](https://user-images.githubusercontent.com/61255483/97236007-6402a300-17a1-11eb-9780-cc01c39eb581.png)

Didn't think to expand the left hand column before creating the screenshots, but the initial time listed was 2:27 before the time at which I saved the log, whereas the actual time tracked was 2:02 due to breaks. I don't recall if this was the case the first day or not, it might have been. A quick look through the code didn't show me where the duration() function was called from, or where it got its input data, although I didn't spend much time searching. :)  I would expect, however, that duration would be the tracked time, not the total time, unless that was intentional?

**Comment by CodeMouse92** [comment]
It SHOULD be tracked time. I'll have to poke at this next chance I get.

**Comment by CodeMouse92** [comment]
Reproduced! It's odd.

1. Start the clock. Wait a few seconds.
2. Pause. Wait a few seconds.
3. Resume. Wait a few more seconds.
4. Pause again.
5. Stop and save.

However, if you skip step 4 and just stop and save, the correct time is stored instead. (@ardunster, this is a workaround until I get this fixed).

Thanks for finding!

**Comment by ardunster** [comment]
oh how peculiar, I wonder why stopping it from a paused state produces a different result. I do usually hit pause before stop and save on any time tracker I've used, whether on purpose or by accident. I'll try to remember to avoid it and see how it works for me. Thanks!

**Comment by ardunster** [comment]
Workaround seems to be effective. I'll let you know if I come up with anything else useful about this.

**Comment by CodeMouse92** [comment]
I've fixed this. Resolution is now on `main`. I have a couple other features to push out before I can release a new version, but you can work directly off of the repository until then.
