### ISSUE TITLE
Rendition of Buttons

### ISSUE THREAD

**Issue by joeld1** [CodeMouse92/timecard#3]
This app is pretty nice! How do I get the bottom 4 buttons to load though?

![Screenshot 2019-12-29 09 12 39](https://user-images.githubusercontent.com/10216562/71560212-9fb2cc00-2a1b-11ea-9762-2883f739674f.png)

**Comment by CodeMouse92** [comment]
Those only have icons. All the buttons have icons, although it looks like none of them are rendering. What is your platform?

Meanwhile, I suppose I could add words to those bottom buttons.

**Comment by joeld1** [comment]
Hi, I'm on a Mac. 

I'm using Python 3.7 as my base environment.

**Comment by CodeMouse92** [comment]
Ah, okay. Yeah, I haven't been able to test on a Mac.

**Comment by CodeMouse92** [comment]
Addressed in 2.0.3.
