### ISSUE TITLE
Seeing 100% CPU usage when tracking time

### ISSUE THREAD

**Issue by cmcode-dev** [CodeMouse92/Timecard#31]
Hi @CodeMouse92 , I am enjoying Timecard. I'm using Flatpak to run it on Manjaro, and unfortunately I'm seeing 100% CPU usage whenever I'm tracking time. The CPU usage goes back to normal when it's not tracking time any more.

I'm looking into the code to see if I can propose a fix for this, but I wanted to bring it to your attention to see if you had any ideas.

quick edit: I'm running it straight from the source code without Flatpak and it is not using 100% CPU any more. So it seems that this could be related to Flatpak somehow. Still investigating.

**Comment by CodeMouse92** [comment]
It's actually an issue I resolved, but haven't yet released. I've had no spare time in 2021. :(

**Comment by cmcode-dev** [comment]
@CodeMouse92 I know what you mean... life can get so busy, sometimes too busy to fix/update code projects. Thanks for responding anyways. I look forward to any future updates to this software when you get the time.

**Comment by CodeMouse92** [comment]
Thanks. I'll try to make a spot for it on my priority list, including reviewing your PR.

By the way, if anything else on [the issues page](https://github.com/CodeMouse92/Timecard/issues) jumps out at you, feel free to submit a PR for it.
