### ISSUE TITLE
Duration Doubled

### ISSUE THREAD

**Issue by joeld1** [CodeMouse92/timecard#4]
Hi, I discovered another issue. 

The app is logging the time as 2x it's original duration. 

![Screenshot 2019-12-29 10 17 32](https://user-images.githubusercontent.com/10216562/71560949-c9bcbc00-2a24-11ea-9e1a-015c4b1c3cc5.png)

**Comment by CodeMouse92** [comment]
So, to clarify, when you click Save, instead of storing 00:00:07, you see 00:00:14 appear in the log instead?

**Comment by CodeMouse92** [comment]
Ah, yeah, duplicated. I have no clue how I missed that!

**Comment by CodeMouse92** [comment]
Addressed in 2.0.3.
