### ISSUE TITLE
TimeDisplay - Typo in f-string in print statement

### ISSUE THREAD

**Issue by joeld1** [CodeMouse92/timecard#8]
It works after removing the = sign.

Thanks again for this app!

![Screenshot 2019-12-29 19 49 10](https://user-images.githubusercontent.com/10216562/71567535-ab7eac80-2a74-11ea-95d8-c39abc7e3e3e.png)

https://github.com/CodeMouse92/timecard/blob/e524401613de36189fd21ea8ae93f96ffda580c3/timecard/interface/timedisplay.py#L79

**Comment by CodeMouse92** [comment]
Oh crikey, I completely forgot to remove that. Eep! New change incoming.

**Comment by CodeMouse92** [comment]
Okay, updated in v2.0.4, which I just pushed to PyPI. Thanks for catching this, and I'm glad you enjoy the app!
